### ISSUE TITLE
quick install errors

### ISSUE THREAD

**Issue by gauta1** [postalhq/postal#380]
Qucik install attempt by using this as per instructions curl https://raw.githubusercontent.com/atech/postal/master/script/install/ubuntu1604.sh | sh

 leads to error.
https://gyazo.com/624b99e1ef92eb0e027c4da7cdeb7043

Successfully installed procodile-1.0.17
2 gems installed
Creating vhost "/postal"
Creating user "postal"
Setting permissions for user "postal" in vhost "/postal"
--2017-10-16 10:41:28-- https://postal.atech.media/packages/stable/latest.tgz
Resolving postal.atech.media (postal.atech.media)... 2a00:67a0🅰️1::1b, 185.22.208.54
Connecting to postal.atech.media (postal.atech.media)|2a00:67a0🅰️1::1b|:443... connected.
ERROR: cannot verify postal.atech.media's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
Issued certificate has expired.
To connect to postal.atech.media insecurely, use `--no-check-certificate'.

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

How should this error be handled?

**Comment by spheron1** [comment]
The SSL certificate on postal.atech.media appears to be valid until the 13th of December 2017, are you sure that the time is set correctly on your server?

What output do you get if you run the following commands:

```
date
openssl s_client -connect postal.atech.media:443 -servername postal.atech.media
```

**Comment by willpower232** [comment]
I verified this was an issue at the time but it seems to have been fixed now.

@gauta1 if you repeat the process, it should work now

**Comment by gauta1** [comment]
I still get error, though a new one. 

Started Procodile supervisor with PID 29214
Generating a 4096 bit RSA private key
..........++
............................++
writing new private key to '/etc/nginx/ssl/postal.key'
-----
Job for nginx.service failed because the control process exited with error code. See "systemctl status nginx.service" and "journalctl -xe" for details.

https://gyazo.com/79edae42c0dcd24fd9796e3c4f641f8d

**Comment by willpower232** [comment]
Please have a look at https://github.com/atech/postal/issues/362, it is likely you'll need to change a `.crt` to `.cert`
